# Site settings
title: Genesor
header-img: img/background_home.jpg
email: ben@sadoma.so
copyright_name: Genesor - Benjamin de Bernardi
description: "I'm Benjamin de Bernardi, a young French Software Engineer and this is my blog! Here, you can find my talks and my articles about IoT, Python, Elasticsearch and more."
baseurl: ""
url: "https://blog.sadoma.so"
twitter_username: Genes0r
github_username:  Genesor
email_username:  ben@sadoma.so

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-76656028-1

# Build settings
markdown: kramdown
highlighter: rouge
google_analytics: UA-76656028-1
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
